name: Zola on GitHub Pages
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: Haru-T/zola-deploy-action@0.16.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
